version: 1.3.2-SNAPSHOT
name: RecentTouch
extensions:
  indi.nonoas.worktools.platform.ui.FuncPaneFactory:
    - indi.nonoas.worktools.recenttouch.RecentTouchController
  indi.nonoas.worktools.platform.common.Searchable:
    - indi.nonoas.worktools.launcher.ExecFileSearcher