id: io.github.nonoas.worktools.platform
name: worktools平台
extensions:
  io.github.nonoas.worktools.platform.ext.FuncPaneFactory:
    - io.github.nonoas.worktools.platform.controller.JdkVersionController
    - io.github.nonoas.worktools.platform.controller.SQLTransferController
    - io.github.nonoas.worktools.platform.controller.TodoListController
    - io.github.nonoas.worktools.platform.controller.FileEncodeController