# yaml-language-server: $schema=./path/to/plugin-schema.jsonversion: 1.3.2-SNAPSHOT
name: 快速启动
id: indi.nonoas.worktools.launcher
extensions:
  indi.nonoas.worktools.platform.ext.FuncPaneFactory:
    - indi.nonoas.worktools.launcher.ExecFileController
  indi.nonoas.worktools.platform.ext.Searchable:
    - indi.nonoas.worktools.launcher.ExecFileSearcher